# Generated by Django 4.2.3 on 2023-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('DE', 'Developer'), ('DS', 'Designer'), ('TE', 'Tester'), ('MR', 'Manager'), ('TL', 'Teamlead')], max_length=2)),
            ],
        ),
    ]
