# Generated by Django 4.2.2 on 2023-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=25)),
                ('empRole', models.CharField(max_length=25)),
                ('empSalary', models.IntegerField()),
            ],
        ),
    ]
